# ===============================
# PROFILE
# ===============================
spring:
  profiles:
    active: local

  # ===============================
  # COMMON PARAMETERS
  # ===============================
  data :
    rest :
      basePath : /api

logging :
  # DEBUG, INFO , ERROR
  level :
    root : INFO

  # Output to a temp_folder/file
  file :
    name: /home/ubuntu/logs/application.log

  pattern :
  # Logging pattern for the console : IT IS OK
  # console : %d{yy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
  
  # Logging pattern for file : DONT WORK, DISABLE WRITE FILE LOG
  # file : %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%

server :
  port : 8080
