# ===============================
# = PARAMETERS
# ===============================

# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core

# ===============================
# = DATA SOURCE
# ===============================
# UNIX or MAC
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password: sa
    data: classpath:data.sql
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl_auto: create-drop
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
  data :
    rest :
      basePath : /api